### ISSUE TITLE
Library used

### ISSUE THREAD

**Issue by Nijwm** [OsmAndroid/ProjectBasics#1]
I have used your library in my app. Check:https://play.google.com/store/apps/details?id=com.nijwm.bunb

**Comment by OsmanDroid** [comment]
Thank you for using my library in your app and I hope it's working fine. 
Check out the latest release version 1.2 it works perfectly and a few more features are included like Copy Text and Share App.

Do add a link of library if you wish.

And I hope this is not a issue anymore and I will close it within 48hrs.

Regards OsmAndroid.

**Comment by Nijwm** [comment]
It's working fine and close the issue. I will be using your library in my
future projects.

**Comment by OsmanDroid** [comment]
Thank you. 😃👍
